// Main loaders
export { youTubeLoader, type YouTubeLoaderOptions } from "./youtube-loader.js";
export { 
  liveYouTubeLoader, 
  type LiveYouTubeLoaderOptions, 
  type YouTubeCollectionFilter,
  type YouTubeBaseCollectionFilter,
  type YouTubeChannelCollectionFilter,
  type YouTubeSearchCollectionFilter,
  type YouTubeEntryFilter,
} from "./live-youtube-loader.js";

// Utility functions
export { 
  fetchYouTubeVideos, 
  searchYouTubeVideos, 
  fetchChannelVideos,
  fetchYouTubePlaylist,
  fetchYouTubePlaylistItems,
  transformYouTubeVideoToVideo,
  transformYouTubeVideosToVideos,
  type YouTubeAPIOptions,
  type YouTubeVideoFetchOptions,
  type YouTubeChannelVideoFetchOptions,
  type YouTubeSearchOptions,
  type YouTubePlaylistFetchOptions,
  type YouTubePlaylistItemFetchOptions,
  type YouTubeAPIResult,
} from "./youtube-api-util.js";

// Schemas and types
export {
  YouTubeThumbnailSchema,
  YouTubeThumbnailsSchema,
  YouTubeVideoSnippetSchema,
  YouTubeVideoContentDetailsSchema,
  YouTubeVideoStatisticsSchema,
  YouTubeVideoStatusSchema,
  YouTubeVideoSchema,
  YouTubeVideoListResponseSchema,
  YouTubeSearchResultSchema,
  YouTubeSearchListResponseSchema,
  YouTubeChannelSchema,
  YouTubePlaylistSnippetSchema,
  YouTubePlaylistStatusSchema,
  YouTubePlaylistContentDetailsSchema,
  YouTubePlaylistSchema,
  YouTubePlaylistListResponseSchema,
  YouTubePlaylistItemSnippetSchema,
  YouTubePlaylistItemContentDetailsSchema,
  YouTubePlaylistItemStatusSchema,
  YouTubePlaylistItemSchema,
  YouTubePlaylistItemListResponseSchema,
  VideoSchema,
  type YouTubeThumbnail,
  type YouTubeThumbnails,
  type YouTubeVideoSnippet,
  type YouTubeVideoContentDetails,
  type YouTubeVideoStatistics,
  type YouTubeVideoStatus,
  type YouTubeVideo,
  type YouTubeVideoListResponse,
  type YouTubeSearchResult,
  type YouTubeSearchListResponse,
  type YouTubeChannel,
  type YouTubePlaylistSnippet,
  type YouTubePlaylistStatus,
  type YouTubePlaylistContentDetails,
  type YouTubePlaylist,
  type YouTubePlaylistListResponse,
  type YouTubePlaylistItemSnippet,
  type YouTubePlaylistItemContentDetails,
  type YouTubePlaylistItemStatus,
  type YouTubePlaylistItem,
  type YouTubePlaylistItemListResponse,
  type Video,
} from "./schema.js";

// Error classes
export {
  YouTubeError,
  YouTubeAPIError,
  YouTubeValidationError,
  YouTubeConfigurationError,
  type YouTubeErrorTypes,
} from "./youtube-errors.js";