name: Test
on:
  pull_request:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.9
      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          cache: "pnpm"
          check-latest: true
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: |
          corepack enable
          pnpm install
      - name: Build
        run: pnpm build
      - name: Check
        run: pnpm check
      - name: Test
        run: pnpm test
